### ISSUE TITLE
Hornet of Despair

### ISSUE THREAD

**Issue by krwminer** [ganymedes01/ErebusIssueTracker#19]
The hitbox or range of Hornet of Despair seems a bit too large.

I was attacked by one and ran inside a cave for shelter where it still proceeded to "hit" me through the stone ceiling of the cave.

I saw the bug report for the Titan Beetle. I just wanted to add this one too.

Edit: I just wanted to add a suggestion that it might be nice if the Hornet of Despair had a chance to drop the sword also. It would encourage people to fight it rather than just avoid it. They do not spawn that often anyways.

**Comment by vadis365** [comment]
They now drop a bottle of anti- venom.
The hit box has be lowered from a size of 3 to 2.5 this may help with the weird collision detection.
