### ISSUE TITLE
Ex Nihilo Silk Mesh recipe conflict

### ISSUE THREAD

**Issue by SanAndreasP** [ganymedes01/ErebusIssueTracker#25]
I have to report a conflict with a crafting recipe for the Silk block. It uses the same recipe as the one for the Silk Mesh (which is used as crafting material for the sieves) from Ex Nihilo and therefore I cannot craft those Silk Meshes. Now I can circumvent this by installing the NoMoreRecipeConflict mod, but would rather like to see a solution to this (possibly changing the recipe of the silk block or have a config option to disable the block, and thus the recipe).

Thanks :)

**Comment by vadis365** [comment]
Sure - we will work something out.
Unless you want to do it - We could do with all the help we can get at the moment.
Coders are severely needed and I know your work is fantastic. :)
I'm surprised Dylan never asked you, seeing as you were an ex-Betweenlands chap and all that.

**Comment by SanAndreasP** [comment]
hm, I could work something out and make a PR.

**Comment by vadis365** [comment]
Dylan has sort of retired to play LoL - he has however left the running of the mod to the coding team.
The main repo for The Erebus is located here:
https://github.com/ganymedes01/TheErebus
If you, or any coders you know, want to help out - or even just dip in to the code to tweak/fix anything it would be awesome.

**Comment by vadis365** [comment]
meh - I'm just going to leave this... and close it.
