### ISSUE TITLE
portal not teleporting

### ISSUE THREAD

**Issue by mafe9191** [ganymedes01/ErebusIssueTracker#32]
hi i have downloaded the erebus mod for the 1.6.4 version of minecraft but when i have tried to use the mod in multiplayer the portal don't teleport to erebus someone can help me with this issue?

**Comment by ganymedes01** [comment]
The 1.6.4 version is no longer developed or supported.
Please update to 1.7.10.

**Comment by mafe9191** [comment]
oh comeone i need help and i prefer the 1.6.4 version please

**Comment by ganymedes01** [comment]
We don't even have the 1.6.4 code anymore, even if I wanted I wouldn't be able to fix your problem =/

**Comment by chylex** [comment]
Funnily enough, I *just* deleted the 1.6.4 workspace of erebus yesterday. Anyways, 1.6.4 is dead, if you prefer it then you will have to prefer a buggy version of erebus.

**Comment by mafe9191** [comment]
in multiplayer the only bug i have found is the altar cause crash of server and the portal if you find the source of the version of erebus for 1.6.4 please send me and i fix the bug for my server
