### ISSUE TITLE
Erebus mobs not spawning in Erebus (may or may not be because of other mods)

### ISSUE THREAD

**Issue by Jeremy9001** [ganymedes01/ErebusIssueTracker#33]
I am running into an issue where no Erebus mobs are spawning in erebus. I do have other mods though so I'm not sure if that's affecting it. I have the lava monsters mod saw I saw those spawning in Erebus wherever lava was but that was it. I am playing on hard difficulty. I should also mention I have orespawn, hardcore ender expansion, special mobs, mo creatures, atum, and custom mob spawner so I don't know if they are affecting erebus. All other dimmensions are fine with appropriate spawns though.

**Comment by chylex** [comment]
Remove custom mob spawner and see if that fixes it.

**Comment by Jeremy9001** [comment]
Whenever I remove custom spawner my game crashes upon loading the world.

**Comment by chylex** [comment]
That's because it is required for Mo' creatures, you will have to remove it for the testing as well.

**Comment by chylex** [comment]
No response from the issue reporter for 5 days, closing because of CMS that is known to cause issues with mob spawning. The issue will be reopened if the issue can be replicated without any other mods.
