### ISSUE TITLE
Bone pile deletes hotbar items

### ISSUE THREAD

**Issue by blarging2000s** [ganymedes01/ErebusIssueTracker#34]
The Block O' Bones is only saving the 3 normal inventory rows and is deleting any item in the hotbar on death. Also items in modded slots are dropped on the ground(baubles, camping mod, etc). TheErebus-0.2a

**Comment by vadis365** [comment]
Update to 0.2b - this issue had been fixed as far as the item loss goes.
Modded slots will still drop and will not be put in the bone block though.
I may change this in the future - but not for now.
