### ISSUE TITLE
Crash with Mariculture on loading of dimension

### ISSUE THREAD

**Issue by Exuraz** [ganymedes01/ErebusIssueTracker#36]
Hi,

Just tried out Erebus today with my modpack that contains Mariculture and when I entered the Erebus portal in the overworld I instantly crashed. After removing Mariculture it worked perfectly fine.

Here's the crashlog:
http://pastebin.com/cWJPp8Q7

Forge: 1403 
Erebus version: 0.2b (latest)
Mariculture version: 1.2.4.2a (latest)

**Comment by vadis365** [comment]
This is an old bug with Mariculture - it tries to generate stuff in the Erebus incorrectly.
Try adding the Erebus (dimension 66 by default) to the Blacklisted dimensions in the Mariculture config.
Also please post a crash report to joshie (Mariculture) and tell him to fix his mod to play nice with other dimensions ;)
I'm closing this as it can be solved easily by doing the above.

**Comment by Exuraz** [comment]
Been a bit busy lately but I just tried that fix and the world is empty except for a layer of bedrock and the portal itself, of which only the frame generated so no way back.
