### ISSUE TITLE
Incompatibility with Iguana Tinker Tweaks

### ISSUE THREAD

**Issue by Galvanize** [ganymedes01/ErebusIssueTracker#37]
Iguana tinker tweaks has a feature that disables some tools, so for example vanilla pickaxes can't mine anything.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2176855-iguanas-tinker-tweaks
http://www.curse.com/mc-mods/minecraft/223248-iguanas-tinker-tweaks

For some reason, when I add Erebus, that feature disappears.

I'm not sure if you code anything into tools but if someone could take a look at that I would apreciate. You can find Boni over at #TinkersConstruct on IRC

Thanks in advance.

**Comment by ganymedes01** [comment]
That's weird, we don't alter the behaviour of the vanilla tools.

I'll install Iguana Tweaks with the Erebus and test it myself

**Comment by ganymedes01** [comment]
One question... what do you mean by "this feature disappears"? You can mine stuff with the vanilla tools? Or is it the Erebus tools that are meant to be disabled but aren't?

**Comment by Galvanize** [comment]
Iguana Tinker Tweaks forces players to progress through Tinkers tools and materials by making other tools useless. So for example if you want to break copper you need to make a flint pickaxe and level it up untill you can break copper and make a copper pick to break iron.
For that end vanilla pickaxes (and some other specific mod items) can be crafted to be used as crafting material for other recipes, but when you try to use them on any block (like dirt) it has no effect, like if you were trying to break Bedrock. It warns players about that behaviour as show in the picture below.

http://prntscr.com/7eqguy

When I add Erebus, that feature disapears, making pickaxes mine as usual and removes the warning message. It seems that it also removes other features iguana shoud add, like replacing a part of an existing Tinker tool, according to Drakay here:
https://github.com/SlimeKnights/IguanaTweaksTConstruct/issues/144

When I asked Boni about this on IRC he said Erebus might be overriding event it shouldnt.

**Comment by ganymedes01** [comment]
I see.
Thanks for the explanation.
Boni is probably right, I'll have to scavenge the erebus code and try to find what could be causing this.

I'll report if I find anything.
Please let me know if you find any other unusual behaviours.

**Comment by Galvanize** [comment]
Thanks a lot for your attention

**Comment by Galvanize** [comment]
Hi,

I'm sorry to bother you again with this, I don't mean to rush you or anything, but I was hoping to start recording my modpack asap and this is the one thing holding me back.

I never modded Minecraft, but I'm a programmer, so I took the liberty of taking a look through the code on both mods.
From what Boni said, I was thinking that the problem should be simple. 

This looks to be the class that disables Vanilla tools:
https://github.com/SlimeKnights/IguanaTweaksTConstruct/blob/master/src/main/java/iguanaman/iguanatweakstconstruct/tweaks/handlers/VanillaToolNerfHandler.java

And I noticed he uses @SubscribeEvent on the functions, and by looking at some tools on Erebus most of them have @Override after extending a vanilla tool.
Like this one for example
https://github.com/ganymedes01/TheErebus/blob/master/src/main/java/erebus/item/ItemPaxel.java

Does that make any sense or am I just being nosy?

**Comment by chylex** [comment]
Can't find Erebus overriding any events, but if he wants the vanilla tool nerf to actually not break if that's the case, he should change iguana tweaks event priorities to be higher.

**Comment by ganymedes01** [comment]
Hey @Galvanize,
I installed the erebus and iguana tweaks together and everything is still working as intended. Vanilla tools still don't break any blocks but the erebus tools still do.

**Comment by Galvanize** [comment]
You are right, I further tested and found out that the bug happens when you install Erebus along with Extra TiC. If you remove either Erebus OR Extra Tic the bug is gone.

I wont bother you with this anymore because it would make no sense to look any further, and I doubpt I would find any answer. Thanks a lot for your attention.

**Comment by ganymedes01** [comment]
If you install just Extra TiC and Iguana Tweaks does the bug still exist?
This might be worth reporting to the Extra TiC devs :3

**Comment by Galvanize** [comment]
Yeah I already talked to Glassmaker, we found an error on the FML log and I reported back to Iguana. So much weirdness =P
