### ISSUE TITLE
Block O' Bones destroys equipped Baubles and some Traveller's Gear accessories

### ISSUE THREAD

**Issue by Zsashas** [ganymedes01/ErebusIssueTracker#39]
Simple as that. If it was in the Baubles slot, it won't be there when you break the Block O' Bones. I've seen this posted in the MCF thread numerous times, but I guess no one posted it here yet. So far, no exceptions to this. Thaumcraft, Botania, Witching Gadgets. Haven't tried Traveller's Gear's accessory slots yet, but I'd rather not risk it until I know it's safe.

**Comment by Zsashas** [comment]
Tested with Traveller's Gear accessories, they drop outside of the Block O' Bones. Which I suppose is better than getting eaten.

**Comment by Gunner76th** [comment]
Is this issue still occurring? I run a survival server, and our modpack relies rather heavily on both baubles useage, as well as Tinker's Traveler's Gear.

**Comment by Zsashas** [comment]
Has there been an update to the Erebus? I haven't seen anything recently.

**Comment by ganymedes01** [comment]
This will be fixed on the next update. I think @vadis365 has one planned for soon
