### ISSUE TITLE
Cant Seem to place or plant Berrybushs 

### ISSUE THREAD

**Issue by Ninjabee-Redtricity** [ganymedes01/ErebusIssueTracker#40]
So I was playing around in the Erebus until I caught what could be bug,When I spotted Heartberry Bushes I picked them up with Shears and got its berry and block,but I cant seem to plant it down on the Grass or Dirt blocks.Is their a solution to it?

**Comment by vadis365** [comment]
Plant them on mud

**Comment by Ninjabee-Redtricity** [comment]
I feel stupid :P

Well Its just that Their was no Information about it on the Erebus Wiki,Im going to help out by Contributing to it.But I got another Question,What are the Use's of the Berries of these Bush's Do heartberrys give you instant health? For Special Magical Brewing Recipes? Theirs no Crafting Recipes For them,So far what I can tell

**Comment by vadis365** [comment]
Jade berries are like 'jade nuggets' 9 craft a piece of jade.
Swamp berries are a food.
Heart berries restore health.
