### ISSUE TITLE
No return portal is generated

### ISSUE THREAD

**Issue by kutschkem** [ganymedes01/ErebusIssueTracker#42]
When entering the Erebus, no return portal was generated. I think what happened is this:

1. Entered Erebus through portal, crashed because of #36 
2. Applied fix for #36 
3. Loaded again, but generation did not place a portal

I suppose that if the game crashes between entering the portal and generating the world, the information that the player just entered the portal is lost.

I don't know if you want to address this, but wanted to report anyways.

**Comment by vadis365** [comment]
Thanks for the report - I'm not sure how we would go about changing anything to prevent this as it was caused by another mod.
