### ISSUE TITLE
Minor issue with TE's Blitz spawning in Erebus

### ISSUE THREAD

**Issue by utoc** [ganymedes01/ErebusIssueTracker#46]
Hello!

I have added The Erebus to my pack and have found that Thermal Foundation new mob Blitz is spawning in The Erebus.  The TF code responsible for this is spawning the blitz in SANDY and PLAINS biomes, that descriptor matches the ones used in Fungal Forest, Subterrainian Savannah and Ulterior Outback.  Is there any way you could blacklist that mob or provide another mechanic to keep all non-Erebus mobs from spawning in The Erebus?  If I need to report this to CoFH instead just let me know!

I'm running The Erebus 0.2b with FML 1448.

**Comment by vadis365** [comment]
Hello,
Only Erebus mobs are coded to spawn in the Erebus - this may not be our fault :)
Thanks for the report .
Closing for now - if we get more reports we'll look into it.
