### ISSUE TITLE
Messup with Mushroom Crafting

### ISSUE THREAD

**Issue by Ninjabee-Redtricity** [ganymedes01/ErebusIssueTracker#47]
When I use 9 Grandma's Shoes Mushrooms to Craft into a block in the Crafting table I get a Kaizer's Finger Mushroom block. And Vice Versa with the Kaizer's Finger Mushrooms to get a Grandma's Shoes Mushroom block. Shouldn't it be the other Way Around?

**Comment by ganymedes01** [comment]
Fixed. Thanks for letting us know.

**Comment by Ninjabee-Redtricity** [comment]
Oh Also would it make sense to have Dark Fruit seeds work in the Organic matter compressor from your surface mod also?

**Comment by ganymedes01** [comment]
Indeed! I'll see what's going on there :3 Thanks for the heads up
