### ISSUE TITLE
The Erebus no longer compatible on Curse Client

### ISSUE THREAD

**Issue by sealchan1** [ganymedes01/ErebusIssueTracker#49]
I updated today to 0.3a Beta via the Curse client and this resulted in a Forge dependency issue, namely, that I needed to update my version of Forge (which the Curse client has at 10.13.3.1401) to support The Erebus mod to...

[21:14:37] [Client thread/ERROR] [FML/]: The mod erebus (Erebus) requires mod versions [Forge@[10.13.4.1448,)] to be available

Is it possible to remove these dependencies so that the out-of-the-box curse client will be able to load this mod?

**Comment by vadis365** [comment]
Hello,

Yes I could do that - but the latest recommended version of forge is the 10.13.4.1488 version.
I'm sure the curse client will update to it in a short time, if not I would recommend updating yourself.
Forge installers are very easy to install on both client and servers and it shouldn't be difficult.
If I was to remove the dependency it would mean when we make changes to the mod that are actually dependent on the version of forge we use - it would crash. Also I would have to edit the code, compile and release the mod again specifically for that reason. Sorry but I don't think we will do that.

Cheers,
Me.

**Comment by ganymedes01** [comment]
That's the recommended forge version for months.
The CurseClient supports it. I've used it myself.

**Comment by vadis365** [comment]
:P

**Comment by vadis365** [comment]
Gany - need to talk to you. Available on skype tonight?

**Comment by ganymedes01** [comment]
Sure!
I'm playing TF2 with a friend, I can pop in later today :3

**Comment by vadis365** [comment]
Thanks mate ;)

**Comment by ganymedes01** [comment]
Also, we should probably get rid of this repo =P
People can report their bugs on the main one. I don't see the point of having two.

What do you think?

**Comment by vadis365** [comment]
yeah -it's a bit of a pain having 2 tbh

**Comment by ganymedes01** [comment]
Just need to update the link on the MCF page. Can you get Dylan to do that?
On the Curse page I can do it myself

**Comment by vadis365** [comment]
We all have access to the OP forums page - I will give you the passwords later.

**Comment by ganymedes01** [comment]
Okay :)
Well update the link. I'm nuking this thing.
